/**
 * MAME 2003 Plus ROM short-code → 한글 게임명 매핑.
 * 부모 ROM 기준, 클론/지역판(j,u,a,b 접미사)은 parent로 자동 폴백.
 * https://archive.org/download/mame-2003-plus-reference-set/roms/ 기준 전수 조사.
 */
const MAME_NAMES: Record<string, string> = {
  // ── # 숫자 ──
  "19xx": "19XX: 운명에 맞선 전쟁",
  "1941": "1941: 카운터 어택",
  "1942": "1942",
  "1943": "1943: 미드웨이 해전",
  "1943kai": "1943改: 미드웨이 해전",
  "1944": "1944: 더 루프 마스터",
  "1945kiii": "1945K III",
  "2020bb": "2020 슈퍼 베이스볼",
  "3countb": "3 카운트 바우트",
  "3stooges": "세 바보",
  "3wonders": "쓰리 원더스",
  "64street": "64번가",
  "720": "720°",
  "88games": "88 올림픽",
  "99lstwar": "'99: 라스트 워",

  // ── A ──
  acrobatm: "어크로뱃 미션",
  aburner2: "애프터 버너 II",
  actfancr: "액트 팬서 사이버네틱",
  adk: "ADK 월드",
  aeroboto: "에어로봇",
  aerofgt: "에어로 파이터즈",
  airbustr: "에어 버스터",
  aircombj: "에어 컴뱃",
  airduel: "에어 듀얼",
  ajax: "에이잭스",
  aliens: "에일리언스",
  aliensyn: "에일리언 신드롬",
  aligator: "앨리게이터 헌트",
  alphaho: "알파 호크",
  alpham2: "알파 미션 II",
  altbeast: "수인전사",
  ambush: "앰부시",
  amojoe: "아미조에",
  androdun: "안드로 듀노스",
  angel: "엔젤",
  aodk: "아그레시브 오브 다크 콤뱃",
  aof: "용호의 권",
  aof2: "용호의 권 2",
  aof3: "용호의 권 3",
  arabianm: "아라비안 매직",
  area51: "에어리어 51",
  argus: "아르고스",
  armwar: "아머드 워리어즈",
  armorcar: "아머 카",
  armwrest: "암 레슬링",
  arkanoid: "알카노이드",
  ashnojoe: "아시노 조",
  ashura: "아수라 블레이드",
  aso: "ASO: 아머드 스크럼 오브젝트",
  assault: "어설트",
  asterix: "아스테릭스",
  astdelu1: "아스테로이드 디럭스",
  asteroid: "아스테로이드",
  astrof: "아스트로 파이터",
  atetris: "아타리 테트리스",
  athena: "아테나",
  avengrgs: "어벤저스 인 갤럭틱 스톰",
  avsp: "에일리언 vs. 프레데터",
  aztarac: "아즈타락",

  // ── B ──
  batrider: "배틀 가레가 2: 배트라이더",
  batsugun: "박총전",
  baddudes: "배드 듀드 vs. 드래곤닌자",
  badlands: "배드랜드",
  bagman: "백맨",
  bakutotu: "바쿠토츠 크지라 대회",
  ballbomb: "볼 봄버",
  bankp: "뱅크 패닉",
  barcade: "바케이드",
  baraduke: "바라듀크",
  batcir: "배틀 서킷",
  batman: "배트맨",
  battlane: "배틀 레인",
  battlnts: "배틀란티스",
  bayroute: "베이루트",
  bbmanw: "봄버맨 월드",
  beastrzr: "비스트 버스터즈",
  beathead: "비트헤드",
  berlwall: "더 베를린 장벽",
  bermudat: "버뮤다 트라이앵글",
  berzerk: "버서크",
  bionicc: "바이오닉 코만도",
  birdtry: "버드 트라이",
  biomtoy: "바이오메캐니컬 토이",
  bjtwin: "방방 볼",
  blaster: "블래스터",
  blazeon: "블레이즈온",
  blazstar: "블레이징 스타",
  blockout: "블록 아웃",
  bloodbro: "블러드 브라더스",
  bloodstm: "블러드스톰",
  bloodwar: "블러드 워리어",
  bloxeed: "블록시드",
  blswhstl: "블레이드 워리어즈",
  blzntrnd: "블레이징 토네이도",
  bm1stmix: "비트매니아 1st MIX",
  bmaster: "블래스트 마스터",
  bogeyman: "보기맨",
  bombjack: "봄 잭",
  bombrman: "봄버맨",
  bonkadv: "봉크의 모험",
  bonzeadv: "본제 어드벤처",
  boogwing: "부그윙",
  boomrang: "부메랑",
  boscomd: "보스코니안",
  btoads: "배틀토즈",
  btime: "버거 타임",
  btlecity: "배틀 시티",
  bublbobl: "버블보블",
  bublbob2: "버블 심포니",
  bubsymph: "버블 심포니",
  bucky: "버키 오헤어",
  bullfgt: "불 파이트",
  burglarx: "버글러 X",
  buriki: "부리키 원",
  bwidow: "블랙 위도우",
  bzone: "배틀존",

  // ── C ──
  cabal: "카발",
  cadash: "카다쉬",
  calorie: "칼로리 군",
  captaven: "캡틴 아메리카",
  captcomm: "캡틴 코만도",
  carnevil: "카니블",
  cawing: "캐리어 에어윙",
  ccastles: "크리스탈 캐슬",
  cclimber: "크레이지 클라이머",
  ccrash: "커맨드 크래시",
  centipede: "센티피드",
  chameleo: "카멜레오",
  champbas: "챔피언 베이스볼",
  champwr: "챔피언 레슬러",
  chelnov: "체르노프",
  chiller: "칠러",
  chinagat: "차이나 게이트",
  choplift: "쵸플리프터",
  chqflag: "체커 플래그",
  chukatai: "추카타이센",
  circusc: "서커스 찰리",
  circus: "서커스",
  cloak: "클로크 & 대거",
  cltchitr: "클러치 히터",
  cninja: "캐비맨 닌자",
  cobracom: "코브라 코만드",
  columns: "컬럼스",
  columns2: "컬럼스 II",
  combasc: "컴뱃 스쿨",
  combat: "컴뱃",
  commando: "코만도",
  compgolf: "경쟁 골프",
  congo: "콩고 봉고",
  contcirc: "컨티넨탈 서커스",
  contra: "콘트라",
  cookrace: "쿡 레이스",
  cop01: "COP 01",
  cotton: "코튼",
  cottonbm: "코튼 부메랑",
  countrun: "카운터 런",
  cps1demo: "CPS1 데모",
  crasher: "크래셔",
  crgolf: "크레이지 골프",
  crimec: "크라임 시티",
  crimfght: "크라임 파이터즈",
  crossbow: "크로스보우",
  crsword: "크로스 소드",
  crusnusa: "크루즌 USA",
  crusnwld: "크루즌 월드",
  crusherm: "크러셔",
  csclub: "캡콤 스포츠 클럽",
  cstlevna: "캐슬바니아",
  cuebrick: "큐브릭",
  cupsocsb: "수퍼 컵 사커",
  cybattlr: "사이버 배틀러",
  cyberlip: "사이버립",
  cybots: "사이보츠",
  cyclwarr: "사이클론 워리어즈",

  // ── D ──
  daioh: "다이오",
  daitorid: "다이토라이드",
  dankuga: "단쿠가",
  daraku: "다라쿠 천사",
  darius: "다라이어스",
  darius2: "다라이어스 II",
  dariusg: "다라이어스 외전",
  darkadv: "다크 어드벤처",
  darkedge: "다크 에지",
  darkseal: "다크 씰",
  darkseal2: "다크 씰 2",
  darwin: "다윈 4078",
  dassault: "데저트 어설트",
  dblaxle: "더블 액슬",
  dblewing: "더블 윙스",
  dbldyn: "더블 드래곤 (네오지오)",
  ddragon: "더블 드래곤",
  ddragon2: "더블 드래곤 2",
  ddragon3: "더블 드래곤 3",
  ddream95: "더블 드래곤 95",
  ddribble: "더블 드리블",
  ddsom: "던전즈 & 드래곤즈: 새도우 오버 미스타라",
  ddtod: "던전즈 & 드래곤즈: 타워 오브 둠",
  deadconx: "데드 커넥션",
  deathcrs: "데스 크레스트",
  decathlt: "데카슬릿",
  defender: "디펜더",
  demonwld: "데몬즈 월드",
  denjinmk: "전진 마카이",
  deroon: "데루운",
  desertwr: "데저트 워",
  detatwin: "데타나 트윈비",
  digdug: "딕덕",
  digdug2: "딕덕 II",
  dimahoo: "디마후",
  dino: "캐딜락 & 다이노사우르스",
  dinorex: "다이노렉스",
  dirtfoxj: "더트 폭스",
  djboy: "DJ보이",
  dkong: "동키콩",
  dkongjr: "동키콩 Jr.",
  dkong3: "동키콩 3",
  dleague: "다이너마이트 리그",
  doapp: "데드 오어 얼라이브++",
  docastle: "도씨의 성",
  dodgem: "닷지엠",
  dogosoke: "독수리 퇴치",
  dogyuun: "도규운",
  dokaben: "도카벤",
  domino: "도미노",
  donpachi: "돈파치",
  ddonpach: "도돈파치",
  dorunrun: "도루돌",
  dotron: "디스크 오브 트론",
  doubledr: "더블 드래곤 (네오지오)",
  driftout: "드리프트 아웃",
  drivedge: "드라이브 엣지",
  drmario: "닥터 마리오",
  drgnbowl: "드래곤 볼",
  drgpunch: "드래곤 펀치",
  dsaber: "드래곤 세이버",
  dstlk: "뱀파이어: 더 나이트 워리어즈",
  dw: "다이너스티 워리어즈",
  dynablst: "다이너 블라스터",
  dynagear: "다이나 기어",
  dynduke: "다이너마이트 듀크",

  // ── E ──
  earthjkr: "어스 조커",
  edf: "E.D.F.: 어스 디펜스 포스",
  elevatora: "엘리베이터 액션",
  elvactr: "엘리베이터 액션 리턴즈",
  empcity: "엠파이어 시티: 1931",
  emeralda: "에메랄디아",
  endurobl: "엔듀로 레이서",
  enforce: "인포스",
  esprade: "에스프레이드",
  eswat: "E-SWAT",
  exctsccr: "엑사이팅 사커",
  excitebk: "엑사이트 바이크",
  exedexes: "엑세드 엑세스",
  exerion: "엑세리온",
  exzisus: "엑시저스",

  // ── F ──
  f1dream: "F1 드림",
  f1gp: "F1 그랑프리",
  f1gpstar: "F1 그랑프리 스타",
  fantasia: "판타지아",
  fantzone: "판타지 존",
  faceoff: "페이스 오프",
  fatfury1: "아랑전설",
  fatfury2: "아랑전설 2",
  fatfursp: "아랑전설 스페셜",
  fatfury3: "아랑전설 3",
  feversos: "피버 SOS",
  ffight: "파이널 파이트",
  fightfev: "파이트 피버",
  fightrol: "파이팅 롤러",
  finalap2: "파이널 랩 2",
  finalap3: "파이널 랩 3",
  finalb: "파이널 블로우",
  finlarch: "파이널 아치",
  finehour: "파이네스트 아워",
  firebarr: "파이어 배럴",
  fireshrk: "파이어 샤크",
  fixeight: "피쎄 에이트",
  flashgal: "플래시 갈",
  flicky: "플리키",
  flipshot: "플립 샷",
  flkatck: "플랙 어택",
  flyball: "플라이볼",
  foodf: "푸드 파이트",
  forgottn: "로스트 월드",
  fpoint: "파이널 포인트",
  freekick: "프리킥",
  frogger: "프로거",
  fshark: "플라잉 샤크",
  funkyjet: "펑키 젯",

  // ── G ──
  gaia: "가이아 크루세이더즈",
  gaiden: "닌자 외전",
  galaga: "갤러가",
  galaga88: "갤러가 '88",
  galaxian: "갤럭시안",
  galmedes: "갈메데스",
  galpanic: "갈 패닉",
  galpani2: "갈 패닉 2",
  garou: "가로우: 늑대의 각인",
  gaunt2: "건틀렛 II",
  gauntlet: "건틀렛",
  gberet: "그린 베레",
  gbusters: "강버스터즈",
  gground: "게인 그라운드",
  ghouls: "대마계촌",
  ghostlop: "고스트 롭",
  ghox: "곡스",
  gigandes: "기간데스",
  gladiatr: "글래디에이터",
  glass: "글래스",
  glfgreat: "골프잉 그레이트",
  gng: "마계촌",
  goldnaxe: "골든 액스",
  goldnax2: "골든 액스: 죽음의 결투",
  goldnax3: "골든 액스 3",
  gokuparo: "극상 패로디우스",
  gradius: "그라디우스",
  gradius2: "그라디우스 II",
  gradius3: "그라디우스 III",
  grdians: "가디언즈 / 전진 마카이 II",
  grainbow: "그레이트 레인보우",
  groundfx: "그라운드 이펙츠",
  growl: "그라울",
  gstream: "건버드 스트림",
  gstrikers: "골 스트라이커즈",
  gtmr: "1000 마일 랠리",
  gtmr2: "마일 스마일즈",
  gulunpa: "구룬파",
  gunbird: "건버드",
  gunbird2: "건버드 2",
  gunblade: "건블레이드 NY",
  gundhara: "건다라",
  gunforce: "건포스",
  gunforce2: "건포스 2",
  gunnail: "건네일",
  gunsmoke: "건 스모크",
  guwange: "구완게",
  gwar: "이카리 III: 더 레스큐",
  gyrodine: "자이로다인",
  gyruss: "자이러스",

  // ── H ──
  halley: "핼리의 혜성",
  hangon: "행온",
  harddriv: "하드 드라이빈",
  hattrick: "햇 트릭",
  hdrivair: "하드 드라이빈 에어본",
  hcastle: "호러 세계의 성",
  helifire: "헬리 파이어",
  hellfire: "헬파이어",
  hexion: "헥시온",
  hippodrm: "히포드롬",
  hook: "후크",
  hoops96: "후프스 '96",
  hotdogst: "핫도그 스톰",
  hpolym84: "하이퍼 올림픽 '84",
  hsf2: "하이퍼 스트리트 파이터 II",
  hunchbak: "꼽추",
  hustler: "허슬러",
  hvoltage: "하이 볼티지",

  // ── I ──
  iemoto: "명인",
  ikari: "이카리",
  ikari3: "이카리 III",
  imagefit: "이미지 파이트",
  imgfight: "이미지 파이트",
  ikarijpb: "이카리 (일본판)",
  inufuku: "이누후쿠",
  invaders: "스페이스 인베이더",
  invadpt2: "스페이스 인베이더 Part II",
  irem: "이렘",
  ironclad: "아이언클래드",
  irrmaze: "이리타팅 메이즈",
  iscream: "아이스크림",
  itaten: "이타텐",

  // ── J ──
  jack: "잭",
  jackal: "자칼",
  jailbrek: "탈옥",
  janshin: "장신",
  jchan: "재키찬",
  jjack: "점핑 잭",
  jjsquawk: "J.J. 스쿼커즈",
  jojo: "죠죠의 기묘한 모험",
  jojoba: "죠죠의 기묘한 모험: 미래의 유산",
  joust: "쥬스트",
  joust2: "쥬스트 2",
  jpark: "쥬라기 공원",
  jrpacman: "주니어 팩맨",
  jumpbug: "점프 버그",
  jungleh: "정글 헌트",
  jungler: "정글러",
  junofrst: "주노 퍼스트",

  // ── K ──
  kabukikl: "가부키 클래시",
  kangaroo: "캥거루",
  karatblz: "가라데 블레이저즈",
  karnov: "카르노프",
  kbash: "배틀 바이커즈",
  kengo: "검호",
  kf10thep: "KOF 10주년",
  kicknrun: "킥 앤 런",
  kikcubic: "킥 큐빅",
  kingdmgp: "킹덤 그랑프리",
  kinst: "킬러 인스팅트",
  kinst2: "킬러 인스팅트 2",
  klax: "클랙스",
  kncljoe: "넉클 조",
  knights: "나이츠 오브 더 라운드",
  knightsh: "나이츠 오브 더 라운드",
  kodure: "코듀어 울프",
  kof94: "KOF '94",
  kof95: "KOF '95",
  kof96: "KOF '96",
  kof97: "KOF '97",
  kof98: "킹오파98",
  kof99: "KOF '99",
  kof2000: "KOF 2000",
  kof2001: "KOF 2001",
  kof2002: "KOF 2002",
  kof2003: "KOF 2003",
  kotm: "킹 오브 더 몬스터즈",
  kotm2: "킹 오브 더 몬스터즈 2",
  kov: "삼국전기",
  kram: "크램",
  krull: "크룰",
  ktiger: "큐소울 타이거",
  ktiger2: "큐소울 타이거 2",
  kungfum: "쿵푸",
  kururin: "쿠루린",

  // ── L ──
  ladybug: "레이디버그",
  labyrnth: "래비린스",
  lastblad: "월화의 검사",
  lastbld2: "월화의 검사 2",
  lastduel: "라스트 듀얼",
  leds2011: "LED 스톰",
  lemmings: "레밍즈",
  leprechn: "레프리콘",
  lethalen: "리썰 인포서즈",
  liberatr: "리버레이터",
  liquidk: "리퀴드 키즈",
  lkage: "전설의 가게",
  lnc: "록앤체이스",
  logicpro: "로직 프로",
  looper: "루퍼",
  lordofk: "로드 오브 킹",
  lostwrld: "잃어버린 세계",
  lotlot: "롯로트",
  loverboy: "러버보이",
  lresort: "라스트 리조트",
  ltorb: "타임 솔져",
  lunarlan: "루나 랜더",
  lwings: "레전더리 윙즈",

  // ── M ──
  macross: "초시공요새 마크로스",
  macross2: "초시공요새 마크로스 II",
  madalien: "매드 에일리언",
  madgear: "매드 기어",
  magdrop2: "매지컬 드롭 2",
  magdrop3: "매지컬 드롭 3",
  magician: "매지션 로드",
  mainevt: "메인 이벤트",
  mainsnk: "메인 SNK",
  majest12: "마제스틱 트웰브",
  majtitle: "메이저 타이틀",
  majtitl2: "메이저 타이틀 2",
  maketrax: "메이크 트랙스",
  manybloc: "매니블록",
  mappy: "매피",
  marble: "마블 매드니스",
  marinedt: "마린 데이트",
  mars: "마스",
  matrim: "매트리밀리",
  maxrpm: "맥스 RPM",
  mazinger: "마징가 Z",
  mclean: "미스터 클린",
  megaman: "록맨: 더 파워 배틀",
  megaman2: "록맨 2: 더 파워 파이터즈",
  megazone: "메가존",
  mercs: "머시너리즈",
  metalb: "메탈 블랙",
  metamrph: "메타모르픽 포스",
  metlclsh: "메탈 클래시",
  metlhawk: "메탈 호크",
  mgolf: "미니 골프",
  miexchng: "머니 아이돌 교환일기",
  mikie: "미키",
  milliped: "밀리피드",
  minivadr: "미니 인베이더",
  mirninja: "미라클 닌자",
  missb2: "미스 버블 2",
  missile: "미사일 커맨드",
  mk: "모탈 컴뱃",
  mk2: "모탈 컴뱃 II",
  mk3: "모탈 컴뱃 3",
  mktrilgy: "모탈 컴뱃 트릴로지",
  mole: "몰",
  momoko: "모모코 120%",
  monsterb: "몬스터 배시",
  mooncrst: "문 크레스타",
  moonpatr: "문 패트롤",
  moonwlk: "문워커",
  moo: "부비 키즈",
  mooua: "와일드 웨스트 C.O.W.-보이즈 오브 무 메사",
  mosaic: "모자이크",
  mpatrol: "문 패트롤",
  mplanets: "매드 플래닛",
  mrdo: "미스터 두",
  mrdrillr: "미스터 드릴러",
  mrdrilr2: "미스터 드릴러 2",
  mrflea: "미스터 플리",
  mrgoemon: "미스터 고에몬",
  mrheli: "미스터 헬리",
  mrjong: "미스터 종",
  mrviking: "미스터 바이킹",
  msh: "마블 슈퍼 히어로즈",
  mshvsf: "마블 슈퍼 히어로즈 vs. 스트리트 파이터",
  mspacman: "미즈 팩맨",
  mslug: "메탈슬러그",
  mslug2: "메탈슬러그 2",
  mslug3: "메탈슬러그 3",
  mslug4: "메탈슬러그 4",
  mslug5: "메탈슬러그 5",
  mslugx: "메탈슬러그 X",
  msword: "매직 스워드",
  mt_bcclp: "보나자 브라더스",
  mugsmash: "머그 스매셔스",
  mustache: "수염 소년",
  mutnat: "뮤턴트 나이트 터틀 어택",
  mvsc: "마블 vs. 캡콤",
  mysticri: "미스틱 리",
  mystwarr: "미스틱 워리어즈",

  // ── N ──
  nam1975: "NAM-1975",
  narc: "나크",
  nastar: "나스타",
  natodefa: "NATO 디펜스",
  nbajam: "NBA 잼",
  nbajamte: "NBA 잼 T.E.",
  nbahangt: "NBA 행타임",
  nbamaxht: "NBA 맥시멈 행타임",
  nbbatman: "닌자 배트맨",
  nemesis: "네메시스",
  neobombe: "네오 봄버맨",
  neocdz: "네오지오 CDZ",
  neodrift: "네오 드리프트 아웃",
  neogeo: "네오지오",
  neopong: "네오퐁",
  nettoh: "네토 데 1만엔",
  nightstr: "나이트 스트라이커",
  ninjak: "닌자 키즈",
  ninjakd2: "닌자군 아수라의 장",
  ninjamas: "닌자 마스터즈",
  ninjaw: "닌자 워리어즈",
  ninjemak: "닌자 에마키",
  nitd: "나이트 인 더 다크",
  nitrobal: "니트로볼",
  nmaster: "네크로노미콘",
  nova2001: "노바 2001",

  // ── O ──
  ohmygod: "오 마이 갓!",
  olibochu: "올리보추",
  omegaf: "오메가 파이터",
  oneshot: "원 샷 원 킬",
  opaopa: "오파오파",
  opwolf: "오퍼레이션 울프",
  opwolf3: "오퍼레이션 울프 3",
  ordyne: "오르다인",
  orlegend: "오리엔탈 레전드",
  olds: "오리엔탈 레전드 스페셜",
  oscarj: "오스카",
  outfxies: "아웃 폭시즈",
  outrun: "아웃런",
  outrunb: "아웃런",
  outzone: "아웃 존",
  overtop: "오버 탑",
  ozmawars: "오즈마 워즈",

  // ── P ──
  pacapp: "팩맨 어레인지먼트",
  pacland: "팩랜드",
  pacman: "팩맨",
  pacmania: "팩매니아",
  pang: "팡",
  pang3: "팡 3",
  pangpoms: "팡팡",
  panicbom: "패닉 봄버",
  paperboy: "페이퍼보이",
  parodius: "패로디우스",
  pbobblen: "퍼즐 보블",
  pbobbl2n: "퍼즐 보블 2",
  pbobbl3u: "퍼즐 보블 3",
  pbobbl4u: "퍼즐 보블 4",
  pblbeach: "비치 발리 볼",
  pendragn: "펜드래건",
  pengo: "펭고",
  pepper2: "페퍼 II",
  phelios: "펠리오스",
  phoenix: "피닉스",
  pigskin: "피그스킨 621AD",
  pingpong: "핑퐁",
  pipedrm: "파이프 드림",
  pipibibs: "피피 & 비비스",
  piratesh: "해적선",
  plegends: "파워 레전드",
  pleiads: "플레이아데스",
  plotting: "플로팅",
  pnickj: "퍼즐 닉",
  pocketrc: "포켓 레이서",
  polepos: "폴 포지션",
  polepos2: "폴 포지션 II",
  policetr: "폴리스 트레이너",
  polygonet: "폴리고넷 커맨더즈",
  popeye: "뽀빠이",
  popnpop: "팝앤팝",
  portman: "포트맨",
  potopoto: "포토포토",
  poundfor: "파운드 포 파운드",
  pow: "P.O.W.: 전쟁 포로",
  powerdrv: "파워 드라이브",
  powerins: "파워 인스팅트",
  prehisle: "원시도 (프리히스토릭 아일)",
  preisle2: "프리히스토릭 아일 2",
  primglex: "프라임 골",
  primrage: "프라이멀 레이지",
  profpac: "프로페서 팩맨",
  progear: "프로기어",
  propcycl: "프로프 사이클",
  prtytime: "파티 타임: 구르메 배틀 퀴즈",
  pspikes: "파워 스파이크즈",
  pspikes2: "파워 스파이크즈 2",
  puckman: "팩맨",
  pulstar: "펄스타",
  punchout: "펀치 아웃!!",
  punisher: "퍼니셔",
  punkshot: "펑크 샷",
  pushman: "푸시맨",
  puyopuy2: "뿌요뿌요 2",
  puzloop: "퍼즐루프",
  puzzledp: "퍼즐 더 팝",
  puzzli2: "퍼즐리 2",

  // ── Q ──
  qbert: "큐버트",
  qix: "큐익스",
  quester: "퀘스터",
  quiz365: "퀴즈 365",
  quizdais: "퀴즈 다이소사쿠",
  quizkof: "퀴즈 KOF",
  quizmoon: "퀴즈 문",

  // ── R ──
  racedrcg: "레이스 드라이빈",
  racinfrc: "에이스 드라이버",
  radarscp: "레이더 스코프",
  raiden: "라이덴",
  raiden2: "라이덴 II",
  raimais: "라이마이스",
  rainbow: "레인보우 아일랜드",
  rallybik: "랠리 바이크",
  rallyx: "랠리 X",
  rambo3: "람보 III",
  rampage: "램페이지",
  rampart: "램파트",
  raphero: "랩히어로",
  rastan: "라스탄 사가",
  rastsag2: "라스탄 사가 2",
  raveracw: "레이브 레이서",
  rayforce: "레이포스",
  raystorm: "레이스톰",
  rbff1: "리얼바웃 아랑전설",
  rbff2: "리얼바웃 아랑전설 2",
  rbffspec: "리얼바웃 아랑전설 스페셜",
  rckman2j: "록맨 2",
  reactor: "리액터",
  realbrk: "리얼 브레이크",
  recalh: "레커밍 호어",
  redclash: "레드 클래시",
  redline: "레드라인 레이서",
  renegade: "열혈경파 쿠니오군",
  rescue: "레스큐",
  retofinv: "리턴 오브 더 인베이더",
  revx: "레볼루션 X",
  rezon: "레존",
  ribbit: "리빗!",
  ridefgtu: "라이더 피처",
  ridgeraj: "릿지 레이서",
  ridger2j: "릿지 레이서 2",
  ridhero: "라이딩 히어로",
  ridingf: "라이딩 파이트",
  ringdest: "링 오브 데스트럭션",
  ringking: "링 킹",
  ringrage: "링 레이지",
  riot: "라이옷",
  riotcity: "라이옷 시티",
  riskchal: "거미줄의 위험한 도전",
  rmpgwt: "램페이지 월드 투어",
  roadblst: "로드 블래스터즈",
  roboarmy: "로보 아미",
  robocop: "로보캅",
  robocop2: "로보캅 2",
  robokid: "아토믹 로보키드",
  robotron: "로보트론: 2084",
  rockclim: "크레이지 클라이머",
  rockmanj: "록맨",
  rockn: "락앤트레드",
  rockrage: "록 레이지",
  rodland: "로드랜드",
  rollergj: "롤러 게임즈",
  rollingc: "롤링 크래시",
  rompers: "롬퍼스",
  rotd: "레이지 오브 더 드래곤즈",
  route16: "루트 16",
  rpunch: "래빗 펀치",
  rthunder: "롤링 썬더",
  rthund2: "롤링 썬더 2",
  rtypej: "R-TYPE",
  rtype: "R-TYPE",
  rtype2: "R-TYPE II",
  rtypeleo: "R-TYPE 레오",
  runark: "런닝 배틀",
  rygar: "아르고스의 전사",

  // ── S ──
  s1945: "스트라이커즈 1945",
  s1945ii: "스트라이커즈 1945 II",
  s1945iii: "스트라이커즈 1945 3",
  sailormn: "세일러문",
  salamand: "사라만다",
  salmndr2: "사라만다 2",
  samsho: "사무라이 쇼다운",
  samsho2: "사무라이 쇼다운 2",
  samsho3: "사무라이 쇼다운 3",
  samsho4: "사무라이 쇼다운 4",
  samsho5: "사무라이 쇼다운 5",
  samsh5sp: "사무라이 쇼다운 5 스페셜",
  savagere: "새비지 레인",
  sbm: "슈퍼 배거맨",
  scontra: "슈퍼 콘트라",
  scramble: "스크램블",
  sdgndmps: "SD건담 사이코 사라마",
  sdi: "SDI: 전략방위구상",
  sengoku: "전국전설",
  sengoku2: "전국전설 2",
  sengoku3: "전국전설 2001",
  sexyparo: "섹시 패로디우스",
  sf1: "스트리트 파이터",
  sf2: "스트리트 파이터 II",
  sf2ce: "스트리트 파이터 II': 챔피언 에디션",
  sf2hf: "스트리트 파이터 II': 하이퍼 파이팅",
  ssf2: "슈퍼 스트리트 파이터 II",
  ssf2t: "슈퍼 스트리트 파이터 II 터보",
  sfa: "스트리트 파이터 알파",
  sfa2: "스트리트 파이터 알파 2",
  sfa3: "스트리트 파이터 알파 3",
  sf3: "스트리트 파이터 III",
  sfiii3: "스트리트 파이터 III: 3rd Strike",
  sgemf: "슈퍼 젬 파이터 미니 믹스",
  shadfrce: "새도우 포스",
  shadoww: "새도우 워리어",
  shdancer: "새도우 댄서",
  shimpact: "슈퍼 하이 임팩트",
  shinobi: "시노비",
  shisen2: "사천성 II",
  shocktr2: "쇼크 트루퍼즈: 2nd Squad",
  shocktro: "쇼크 트루퍼즈",
  shogwarr: "쇼군 워리어즈",
  shuuz: "슈즈",
  shuuz2: "슈즈 2",
  simpsons: "심슨 가족",
  simps2p: "심슨 2인용",
  sinistar: "시니스타",
  skullxbo: "스컬 크로스본즈",
  skyadvnt: "스카이 어드벤처",
  skyalert: "스카이 얼럿",
  slammast: "새터데이 나이트 슬램 마스터즈",
  slapfght: "슬랩 파이트",
  slapsht: "슬램 팩",
  slither: "슬리더",
  slyspy: "시크릿 에이전트",
  smash: "스매시 TV",
  smashtv: "스매시 TV",
  snowbro2: "스노우 브라더스 2",
  snowbros: "스노우 브라더스",
  snowbros2: "스노우 브라더스 2",
  socbrawl: "사커 브롤",
  solarfox: "솔라 폭스",
  solarq: "솔라 퀘스트",
  soldivid: "솔 디바이드",
  solomon: "솔로몬의 열쇠",
  solvalou: "솔발로우",
  sonic: "세가 소닉 더 헤지호그",
  sonicwi: "에어로 파이터즈",
  sonicwi2: "에어로 파이터즈 2",
  sonicwi3: "에어로 파이터즈 3",
  sonson: "손손",
  sooger: "사기꾼",
  sor: "스트리트 오브 레이지",
  sorr: "스트리트 오브 레이지 리메이크",
  spaceinv: "스페이스 인베이더",
  spacedx: "스페이스 인베이더 DX",
  spcenctr: "스페이스 엔카운터",
  spcforce: "스페이스 포스",
  spclord: "스페셜 크리미널 인베스티게이션",
  spectar: "스펙타",
  speedbal: "스피드볼",
  speedspn: "스피드 스핀",
  spelunkr: "스펠렁커",
  spelunk2: "스펠렁커 2",
  spf2t: "슈퍼 퍼즐 파이터 II 터보",
  spinmast: "스핀 마스터",
  splatter: "스플래터하우스",
  spnchout: "슈퍼 펀치아웃!!",
  sprint2: "스프린트 2",
  sprint4: "스프린트 4",
  sqbert: "큐버트",
  srumbler: "스트라이더 험블러",
  ssi: "S.S.I.",
  ssideki: "슈퍼 사이드킥스",
  ssideki2: "슈퍼 사이드킥스 2",
  ssideki3: "슈퍼 사이드킥스 3",
  ssideki4: "슈퍼 사이드킥스 4",
  sss: "슈퍼 스타 솔져",
  sspirits: "사무라이 스피리츠",
  ssriders: "선셋 라이더즈",
  stakwin: "스테익스 위너",
  stakwin2: "스테익스 위너 2",
  starblad: "스타블레이드",
  starforc: "스타포스",
  stargrd: "스타 가드",
  starwars: "스타 워즈",
  stdragon: "스틸 드래곤",
  stonebal: "스톤볼",
  stratvox: "스트래토 복스",
  strider: "스트라이더 히류",
  strider2: "스트라이더 2",
  strhoop: "스트리트 후프",
  streetsm: "스트리트 스마트",
  superman: "슈퍼맨",
  suprtrio: "슈퍼 트리오",
  superpac: "슈퍼 팩맨",
  superqix: "슈퍼 큐익스",
  superspy: "슈퍼 스파이",
  suprleag: "슈퍼 리그",
  suprloco: "슈퍼 로코모티브",
  suratk: "서프라이즈 어택",
  surpratk: "서프라이즈 어택",
  svc: "SNK vs. 캡콤: SVC 카오스",
  suzuk8h: "스즈카 8시간",
  syvalion: "사이발리온",

  // ── T ──
  taikodon: "태고의 달인",
  tail2nos: "테일 투 노즈",
  taito: "타이토",
  tank8: "탱크 8",
  tankfrce: "탱크 포스",
  taotaido: "타오타이도",
  tapper: "탭퍼",
  targeth: "타겟 히트",
  tattass: "타투 어쌔신",
  tbowl: "테크모 볼",
  tbyahhoo: "투 바이 야후",
  tceptor: "썬더 셉터",
  tdfever: "터치다운 피버",
  tdragon: "썬더 드래곤",
  tdragon2: "썬더 드래곤 2",
  tekipaki: "테키파키",
  tekken: "철권",
  tekken2: "철권 2",
  tekken3: "철권 3",
  tempest: "템페스트",
  tengai: "천외마경 진전(텐가이)",
  terracre: "테라 크레스타",
  tetris: "테트리스",
  theglob: "더 글로브",
  thndzone: "썬더 존",
  thunderx: "썬더 크로스",
  thunderl: "썬더 & 라이트닝",
  tigeroad: "타이거 로드",
  timber: "팀버",
  timecris: "타임 크라이시스",
  timekill: "타임 킬러즈",
  timeplt: "타임 파일럿",
  timesold: "타임 솔저",
  tinklpit: "틴클 핏",
  tkdensho: "투신전",
  tkmmpzdm: "토코메키 메모리얼",
  tmek: "T-MEK",
  tmnt: "닌자 거북이",
  tmnt2: "닌자 거북이 2",
  tndrcade: "썬더 케이드",
  tnexspce: "더 넥스트 스페이스",
  tnk3: "TNK III",
  toadaged: "배틀토즈",
  toki: "토키",
  tokio: "토키오",
  topgun: "탑건",
  tophuntr: "탑 헌터: 로디 & 캐시",
  topranku: "탑 랭킹",
  topsecrt: "시크릿 에이전트",
  tottall: "토탈리퀘이트",
  touchgo: "터치 앤 고",
  toutrun: "터보 아웃런",
  toypop: "토이팝",
  tp2m32: "테츠진 포켓",
  trog: "트로그",
  trojan: "트로잔",
  tron: "트론",
  truxton: "트럭스턴",
  truxton2: "트럭스턴 II",
  turfmast: "네오 터프 마스터즈",
  turbo: "터보",
  turbofrc: "터보 포스",
  turtles: "거북이",
  twincobr: "트윈 코브라",
  twinbee: "트윈비",
  twinhawk: "트윈 호크",

  // ── U ──
  uballoon: "울트라 벌룬",
  uccopsu: "언더커버 캅스",
  ultraman: "울트라맨",
  umk3: "얼티밋 모탈 컴뱃 3",
  uopoko: "퍼즐 우오포코",
  upndown: "업앤다운",
  usvsthem: "US vs. Them",

  // ── V ──
  valtric: "발트릭",
  vamphalf: "뱀프 x1/2",
  varth: "바스: 오퍼레이션 썬더스톰",
  vendetta: "벤데타",
  vfive: "V-Five",
  vhunt2: "뱀파이어 헌터 2",
  vhuntj: "뱀파이어 헌터",
  victlapw: "에이스 드라이버: 빅토리 랩",
  victroad: "이카리 2: 빅토리 로드",
  videopin: "비디오 핀볼",
  viewpoin: "뷰포인트",
  vigilant: "비질란테",
  vimana: "비마나",
  vindictr: "빈디케이터즈",
  viofight: "바이올런스 파이트",
  viostorm: "바이올런트 스톰",
  vsav: "뱀파이어 세이버",
  vsav2: "뱀파이어 세이버 2",
  vsgshoe: "VS. 건슈",
  vulcan: "그라디우스 II",
  vulgus: "발거스",

  // ── W ──
  wacko: "와코",
  wakuwak7: "와쿠와쿠 7",
  wargods: "워 갓즈",
  warlords: "워로즈",
  wardner: "와드너",
  wboy: "원더보이",
  wboy3: "원더보이 3",
  wcbowl: "월드 챔피언십 볼링",
  wh1: "월드 히어로즈",
  wh2: "월드 히어로즈 2",
  whp: "월드 히어로즈 퍼펙트",
  wildfang: "와일드 팽",
  wiping: "와이핑",
  wits: "위트",
  wjammers: "윈드잼머스",
  wndrmomo: "원더 모모",
  wof: "삼국지: 용의 왕좌",
  wondl96: "원더리그 96",
  woodpek: "우드페커",
  wpksoc: "월드 PK 사커",
  wrally: "월드 랠리",
  wrally2: "월드 랠리 2",
  wrestwar: "레슬 워",
  wrofaero: "에어로 파이터",

  // ── X ──
  xevious: "제비우스",
  xevi3dg: "제비우스 3D/G",
  xexex: "제트엑스",
  xfiles: "X-파일",
  xmen: "엑스맨",
  xmcota: "엑스맨: 칠드런 오브 디 아톰",
  xmvsf: "엑스맨 vs. 스트리트 파이터",
  xorworld: "크소르 월드",
  xsleena: "소드 오브 더 버서크",
  xxmissio: "XX미션",
  xybots: "자이봇츠",

  // ── Y ──
  yard: "10야드 파이트",
  yiear: "이얼 쿵푸",
  yokaidko: "요괴 도총",
  youkaidk: "요괴대전쟁",
  youma: "요마닌자",

  // ── Z ──
  zaxxon: "잭슨",
  zedblade: "제드 블레이드",
  zektor: "제크터",
  zeropnt: "제로 포인트",
  zeropnt2: "제로 포인트 2",
  zerowing: "제로 윙",
  zerozone: "제로 존",
  zigzag: "지그재그",
  zingzip: "징징 집",
  zombraid: "좀비 레이드",
  zookeep: "주키퍼",
  zupapa: "주파파!",
  zwackery: "즈와커리",
  zzyzzyxx: "지지지크스",
};

// ────────────────────────────────────────────────────────────────
// 카테고리 시스템
// ────────────────────────────────────────────────────────────────

export type GameCategory = "fighting" | "action" | "shooting" | "puzzle" | "sports" | "etc";

export const CATEGORY_INFO: Record<GameCategory, { label: string; icon: string; order: number }> = {
  fighting: { label: "격투", icon: "⚔️", order: 1 },
  action: { label: "액션", icon: "💥", order: 2 },
  shooting: { label: "슈팅", icon: "🚀", order: 3 },
  puzzle: { label: "퍼즐", icon: "🧩", order: 4 },
  sports: { label: "스포츠", icon: "⚽", order: 5 },
  etc: { label: "기타", icon: "🎮", order: 6 },
};

/**
 * ROM shortcode → 카테고리 매핑.
 * 여기에 없는 게임은 "etc" 로 폴백.
 */
const GAME_CATEGORIES: Record<string, GameCategory> = {
  // ── 격투 (Fighting) ──────────────────────────────────────────
  // Street Fighter 시리즈
  sf2: "fighting",
  sf2ce: "fighting",
  sf2t: "fighting",
  sf2hf: "fighting",
  ssf2: "fighting",
  ssf2t: "fighting",
  sfa: "fighting",
  sfa2: "fighting",
  sfa3: "fighting",
  sfiii: "fighting",
  sfiii2: "fighting",
  sfiii3: "fighting",
  sfiii3n: "fighting",
  // KOF 시리즈
  kof94: "fighting",
  kof95: "fighting",
  kof96: "fighting",
  kof97: "fighting",
  kof98: "fighting",
  kof99: "fighting",
  kof2000: "fighting",
  kof2001: "fighting",
  kof2002: "fighting",
  kof2003: "fighting",
  // 사무라이 쇼다운 시리즈
  samsho: "fighting",
  samsho2: "fighting",
  samsho3: "fighting",
  samsho4: "fighting",
  samsho5: "fighting",
  samsh5sp: "fighting",
  // SNK 격투
  garou: "fighting",
  lastblad: "fighting",
  lastbld2: "fighting",
  rbff2: "fighting",
  rbffspec: "fighting",
  fatfursp: "fighting",
  fatfury1: "fighting",
  fatfury2: "fighting",
  fatfury3: "fighting",
  aof: "fighting",
  aof2: "fighting",
  aof3: "fighting",
  wh1: "fighting",
  wh2: "fighting",
  wh2j: "fighting",
  whp: "fighting",
  matrim: "fighting",
  svc: "fighting",
  kizuna: "fighting",
  savagere: "fighting",
  breakers: "fighting",
  breakrev: "fighting",
  // Marvel / Capcom 크로스오버
  msh: "fighting",
  mshvsf: "fighting",
  mvsc: "fighting",
  xmcota: "fighting",
  xmvsf: "fighting",
  // 기타 격투
  dstlk: "fighting",
  nwarr: "fighting",
  vsav: "fighting",
  vsav2: "fighting",
  cybots: "fighting",
  sfex: "fighting",
  sfex2: "fighting",
  sgemf: "fighting",
  ringdest: "fighting",
  jgolds: "fighting",
  waku7: "fighting",
  turfmast: "fighting",
  kabukikl: "fighting",
  karnovr: "fighting",
  doubledr: "fighting",
  fightfev: "fighting",
  galaxyfg: "fighting",
  gowcaizr: "fighting",
  tekken: "fighting",
  tekken2: "fighting",
  tekken3: "fighting",
  soulclbr: "fighting",
  mk: "fighting",
  mk2: "fighting",
  mk3: "fighting",
  umk3: "fighting",

  // ── 액션 (Action / Beat'em Up / Run & Gun) ──────────────────
  // 메탈슬러그 시리즈
  mslug: "action",
  mslug2: "action",
  mslug3: "action",
  mslug4: "action",
  mslug5: "action",
  mslugx: "action",
  // 벨트스크롤 액션
  tmnt: "action",
  tmnt2: "action",
  simpsons: "action",
  xmen: "action",
  dino: "action",
  punisher: "action",
  nbbatman: "action",
  avsp: "action",
  ddsom: "action",
  ddtod: "action",
  captcomm: "action",
  knights: "action",
  ffight: "action",
  sengoku3: "action",
  mutnat: "action",
  vendetta: "action",
  critcrsh: "action",
  bucky: "action",
  metamrph: "action",
  mysticwr: "action",
  gauntlet: "action",
  gauntlt2: "action",
  grdians: "action",
  // 플랫폼 / 기타 액션
  bublbobl: "action",
  jjsquawk: "action",
  snowbro2: "action",
  snowbros: "action",
  neobombe: "action",
  wboy3: "action",
  "64street": "action",
  spinmast: "action",
  tophntr: "action",
  nam1975: "action",
  shocktro: "action",
  // 건슈팅 / 메탈슬러그 류
  gunbird: "action",
  gunbird2: "action",

  // ── 슈팅 (Shooting / Shmup) ─────────────────────────────────
  "1941": "shooting",
  "1942": "shooting",
  "1943": "shooting",
  "1943kai": "shooting",
  "1944": "shooting",
  "1945kiii": "shooting",
  "19xx": "shooting",
  ddonpach: "shooting",
  donpachi: "shooting",
  progear: "shooting",
  s1945iii: "shooting",
  tengai: "shooting",
  guwange: "shooting",
  esprade: "shooting",
  dimahoo: "shooting",
  batsugun: "shooting",
  aerofgt: "shooting",
  aero: "shooting",
  blazstar: "shooting",
  pulstar: "shooting",
  strikers: "shooting",
  strhoop: "shooting",
  twinbee: "shooting",
  gradius: "shooting",
  gradius2: "shooting",
  gradius3: "shooting",
  grdius2: "shooting",
  grdius3: "shooting",
  lifefrce: "shooting",
  salamand: "shooting",
  parodius: "shooting",
  rtype: "shooting",
  rtype2: "shooting",
  rtypeleo: "shooting",
  darius: "shooting",
  darius2: "shooting",
  raiden: "shooting",
  raiden2: "shooting",
  raidendx: "shooting",
  varth: "shooting",
  twinbrat: "shooting",
  mmatrix: "shooting",

  // ── 퍼즐 (Puzzle) ───────────────────────────────────────────
  puyopuy2: "puzzle",
  pbobblen: "puzzle",
  pang3: "puzzle",
  magdrop3: "puzzle",
  magdrop2: "puzzle",
  puzzledp: "puzzle",
  puzzloop: "puzzle",
  smpuzzlr: "puzzle",
  columns: "puzzle",
  columns2: "puzzle",
  tetris: "puzzle",
  hatris: "puzzle",
  puchicar: "puzzle",
  bustamov: "puzzle",
  bjourney: "puzzle",
  janshin: "puzzle",
  zupapa: "puzzle",

  // ── 스포츠 (Sports) ─────────────────────────────────────────
  wjammers: "sports",
  nbahangt: "sports",
  nbajam: "sports",
  nbajamte: "sports",
  "2020bb": "sports",
  "3countb": "sports",
  "88games": "sports",
  ssideki: "sports",
  ssideki2: "sports",
  ssideki3: "sports",
  ssideki4: "sports",
  socbrawl: "sports",
  goalx3: "sports",
  pgoal: "sports",
  slapfght: "sports",
  slapshot: "sports",
  wwfmania: "sports",
  wwfwfest: "sports",
  kinst: "fighting",
  kinst2: "fighting",
};

const ARCADE_CORES = new Set(["mame2003", "mame2003_plus", "arcade", "fbneo"]);
const ROM_FILENAME_EXTENSION_PATTERN = /\.\w+$/;
const CLONE_SUFFIX_PATTERN = /(?:[_-]?[a-z])$/;
const MAX_CLONE_SUFFIX_FALLBACK_STEPS = 2;

function stripRomExtension(filename: string) {
  return filename.replace(ROM_FILENAME_EXTENSION_PATTERN, "");
}

function hasLookupEntry<T>(lookup: Record<string, T>, key: string) {
  return Object.prototype.hasOwnProperty.call(lookup, key);
}

function resolveArcadeLookupKey<T>(lookup: Record<string, T>, filename: string) {
  const base = stripRomExtension(filename).toLowerCase();

  if (hasLookupEntry(lookup, base)) {
    return base;
  }

  let candidate = base;

  for (let step = 0; step < MAX_CLONE_SUFFIX_FALLBACK_STEPS; step += 1) {
    const trailingCharacter = candidate.at(-1);
    const previousCharacter = candidate.at(-2);

    if (trailingCharacter && previousCharacter === trailingCharacter) {
      break;
    }

    const nextCandidate = candidate.replace(CLONE_SUFFIX_PATTERN, "");

    if (nextCandidate === candidate || nextCandidate.length < 3) {
      break;
    }

    candidate = nextCandidate;

    if (hasLookupEntry(lookup, candidate)) {
      return candidate;
    }
  }

  return null;
}

export function isArcadeCore(core: string) {
  return ARCADE_CORES.has(core);
}

export function resolveArcadeLookupValue<T>(filename: string, lookup: Record<string, T>): T | null {
  const key = resolveArcadeLookupKey(lookup, filename);
  return key ? lookup[key] : null;
}

/**
 * ROM shortcode의 카테고리를 반환. 매핑에 없으면 "etc".
 */
export function getRomCategory(filename: string, core: string): GameCategory {
  if (!isArcadeCore(core)) {
    return "etc";
  }

  return resolveArcadeLookupValue(filename, GAME_CATEGORIES) ?? "etc";
}

/**
 * Convert a ROM filename like "mslug3.zip" or "Super_Mario_Bros.nes"
 * into a human-friendly display name.
 */
export function parseRomName(filename: string, core: string): string {
  // Strip extension
  const base = stripRomExtension(filename);

  // For MAME/arcade cores, try the lookup table first
  if (isArcadeCore(core)) {
    const known = resolveArcadeLookupValue(filename, MAME_NAMES);
    if (known) return known;
  }

  // Fallback: humanize the filename
  return base
    .replace(/[_-]/g, " ") // underscores/hyphens → spaces
    .replace(/([a-z])([A-Z])/g, "$1 $2") // camelCase split
    .replace(/\s+/g, " ") // collapse whitespace
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase()); // title case
}
