/**
 * libretro CDN 썸네일 URL 검증 및 자동 매칭 스크립트
 *
 * 접근 방식:
 * 1. MAME listxml에서 ROM shortcode → English name 매핑 가져오기
 * 2. 없으면 알려진 MAME 게임 DB에서 조회
 * 3. CDN HEAD 요청으로 썸네일 존재 확인
 */
import * as https from "https";

// ── MAME ROM 숏코드 → 영어 이름 (직접 추가 + MAME DB) ──
// 이것이 최종 결과물: game-thumbnails.ts에 추가할 매핑
const NEW_MAME_THUMBNAIL_NAMES: Record<string, string> = {
  // ── CPS1 ──
  dynwar: "Dynasty Wars (World)",
  kod: "The King of Dragons (World 910711)",
  mbombrd: "Mega Man - Battle and Chase (World)",
  mtwins: "Mega Twins (World 900619)",
  nemo: "Nemo (World 901130)",
  pnickj: "Pnickies (Japan 940628)",
  unsquad: "U.N. Squadron (World)",
  willow: "Willow (World)",

  // ── CPS2 ──
  ecofghtr: "Eco Fighters (World 931203)",
  gigawing: "Giga Wing (USA 990222)",
  mmatrix: "Mars Matrix - Hyper Solid Shooting (USA 000412)",
  mpang: "Mighty! Pang (Euro 001010)",
  nwarr: "Night Warriors - Darkstalkers' Revenge (Euro 950316)",
  pzloop2: "Puzz Loop 2 (Euro 010302)",
  ringdest: "Ring of Destruction - Slammasters II (Euro 940902)",
  sfz2al: "Street Fighter Alpha 2 (USA 960430)",
  vhunt2: "Vampire Hunter 2 - Darkstalkers' Revenge (Japan 970929)",
  vsav2: "Vampire Savior 2 - The Lord of Vampire (Japan 970913)",

  // ── CPS3 ──
  redearth: "Red Earth (Euro 961121)",
  sfiii: "Street Fighter III - New Generation (Euro 970204)",
  sfiii2: "Street Fighter III 2nd Impact - Giant Attack (USA 970930)",

  // ── NeoGeo ──
  alpham2: "Alpha Mission II _ ASO II - Last Guardian",
  bangbead: "Bang Bead",
  bjourney: "Blue's Journey _ Raguy",
  breakrev: "Breakers Revenge (set 1)",
  bstars: "Baseball Stars Professional",
  bstars2: "Baseball Stars 2",
  burningf: "Burning Fight (set 1)",
  crswd2bl: "Crossed Swords 2",
  doubledr: "Double Dragon (Neo-Geo)",
  eightman: "Eight Man (set 1)",
  ganryu: "Ganryu _ Musashi Ganryuki",
  gpilots: "Ghost Pilots",
  irrmaze: "The Irritating Maze",
  lbowling: "League Bowling",
  maglord: "Magician Lord (set 1)",
  mutnat: "Mutation Nation",
  ncombat: "Ninja Combat",
  ncommand: "Ninja Commando",
  neodrift: "Neo Drift Out - New Technology",
  neogeo: "Neo Geo BIOS",
  neomrdo: "Neo Mr. Do!",
  nitd: "Nightmare in the Dark",
  preisle2: "Prehistoric Isle 2",
  roboarmy: "Robo Army",
  rotd: "Rage of the Dragons",
  samsh5fe: "Samurai Shodown V Special",
  sdodgeb: "Super Dodge Ball",
  sengoku2: "Sengoku 2 _ Sengoku Denshou 2",
  shocktr2: "Shock Troopers - 2nd Squad",
  ssideki4: "The Ultimate 11 - SNK Football Championship _ Tokuten Ou - Honoo no Libero",
  superspy: "The Super Spy",
  trally: "Thrash Rally",
  twinspri: "Twinkle Star Sprites",

  // ── toaplan_cave_stg ──
  akatana: "Akai Katana",
  alcon: "Alcon _ Slap Fight",
  ddp3: "DoDonPachi III",
  ddpdfk: "DoDonPachi Dai-Fukkatsu",
  ddpsdoj: "DoDonPachi SaiDaiOuJou",
  deathsml: "Deathsmiles",
  dfkbl: "DoDonPachi Dai-Fukkatsu Black Label",
  dogyuun: "Dogyuun",
  dsmbl: "Deathsmiles Mega Black Label",
  espgal: "ESP Galuda",
  espgal2: "ESP Galuda II",
  feversos: "Fever SOS",
  fshark: "Flying Shark",
  futari15: "Mushihime-sama Futari 1.5",
  futaribl: "Mushihime-sama Futari Black Label",
  grindstm: "Grind Stormer",
  ibara: "Ibara",
  ibarablk: "Ibara Kuro - Black Label",
  ket: "Ketsui - Kizuna Jigoku Tachi",
  mmpork: "Much Much Pork!",
  mushisam: "Mushihime-sama",
  pinkswts: "Pink Sweets - Ibara Sorekara",
  tigerh: "Tiger Heli",
  twinhawk: "Twin Hawk",
  vimana: "Vimana",

  // ── fbneo (주요 인기 게임) ──
  actfancr: "Act-Fancer Cybernetick Hyper-Nature",
  agallet: "Air Gallet",
  airwolf: "Airwolf",
  aligator: "Alligator Hunt",
  amidar: "Amidar",
  aquajack: "Aqua Jack",
  arknoid2: "Arkanoid 2 - Revenge of Doh",
  armorcar: "Armored Car (set 1)",
  armwrest: "Arm Wrestling",
  astdelux: "Asteroids Deluxe (rev 2)",
  astorm: "Astro Storm",
  atetris: "Tetris (Atari)",
  aurail: "Aurail (set 1, US)",
  avengers: "Avengers (set 1, World)",
  avspirit: "Avenging Spirit",
  badlands: "Bad Lands",
  bbros: "Bomb Bee",
  bgaregga: "Battle Garegga (Europe _ USA _ Japan _ Asia)",
  biomtoy: "Biomechanical Toy (Ver. 1.0.1885)",
  blktiger: "Black Tiger",
  blstroid: "Blasteroids (rev 1)",
  blswhstl: "Blades of Steel (version 1)",
  bnj: "Boogie Wings _ Boogie Wings",
  bogeyman: "Bogey Manor",
  bongo: "Bongo",
  boogwing: "Boogie Wings",
  brkthru: "Break Thru (US)",
  bubbles: "Bubbles",
  buckrog: "Buck Rogers - Planet of Zoom",
  bwidow: "Black Widow",
  carnival: "Carnival (set 1)",
  ccastles: "Crystal Castles (version 4)",
  centiped: "Centipede (revision 4)",
  chaknpop: "Chack'n Pop",
  chasehq: "Chase H.Q. (World)",
  chinagat: "China Gate (US)",
  choplift: "Choplifter",
  citycon: "City Connection (set 1)",
  ckong: "Crazy Kong (set 1)",
  ckongpt2: "Crazy Kong Part II (set 1)",
  cleopatr: "Cleopatra Fortune",
  congo: "Congo Bongo (set 1)",
  cotton: "Cotton (set 1, World)",
  ctribe: "The Combatribes (US)",
  cyvern: "Cyvern (US)",
  darkseal: "Dark Seal (World)",
  dassault: "Desert Assault (US)",
  dbreed: "Dragon Breed (World)",
  dbz: "Dragon Ball Z - V.R.V.S. (Japan)",
  dbz2: "Dragon Ball Z 2 - Super Battle (Japan)",
  ddcrew2: "D.D. Crew 2 (Japan)",
  ddux: "D.D. Crew (World)",
  deadconx: "Dead Connection (World)",
  docastle: "Mr. Do's Castle (set 1)",
  dondokod: "Don Doko Don (World)",
  drgnbstr: "Dragon Blaster",
  drtoppel: "Dr. Toppel Adventure (Japan)",
  dsaber: "Dragon Saber - After Story of Dragon Spirit",
  dsoccr94: "Dream Soccer '94 (Japan)",
  dynagear: "Dyna Gears (set 1)",
  edrandy: "Edward Randy",
  elevator: "Elevator Action (World)",
  elvactr: "Elevator Action Returns (World)",
  enduror: "Enduro Racer (Mask ROM version)",
  eprom: "Escape from the Planet of the Robot Monsters (set 1)",
  exedexes: "Exed Exes",
  fantzn2: "Fantasy Zone II - The Tears of Opa-Opa",
  fastlane: "Fast Lane",
  flicky: "Flicky (set 1)",
  foodf: "Food Fight",
  ga2: "Gaia Crusaders",
  gaia: "Gaia Crusaders",
  galivan: "Galivan",
  galmedes: "Galmedes (Japan)",
  gangwars: "Gang Wars (US)",
  gaplus: "Galaga 3 (set 1)",
  gaunt22p: "Gauntlet II (2 Players)",
  gauntlet2p: "Gauntlet (2 Players)",
  gblchmp: "Galactic Warriors",
  geebeeg: "Gee Bee (UK)",
  gground: "Gain Ground (World)",
  ghostb: "Ghosts'n Goblins (World)",
  gijoe: "G.I. Joe (World, EAB, set 1)",
  gnbarich: "Gunbarich",
  godzilla: "Godzilla",
  gogomile: "Gogomile",
  gstream: "G-Stream G2020",
  gtmr2: "Great 1000 Miles Rally 2",
  gunlock: "Gunlock",
  gunnail: "GunNail (Japan)",
  gyruss: "Gyruss",
  hbarrel: "Heavy Barrel",
  heatbrl: "Heat Barrel",
  hharry: "Hammerin' Harry (World)",
  hitice: "Hit the Ice (US)",
  hopmappy: "Hoppin' Mappy",
  horekid: "Hopping Mappy",
  horizon: "Horizon",
  hvysmsh: "Heavy Smash (World)",
  inthunt: "In the Hunt (World)",
  jailbrek: "Jail Break",
  jedi: "Return of the Jedi",
  journey: "Journey",
  junglek: "Jungle King (Japan)",
  junofrst: "Juno First",
  kangaroo: "Kangaroo",
  kchamp: "Karate Champ (US)",
  kick: "Kick Rider",
  kicker: "Kicker",
  kingball: "King of the Ball",
  krull: "Krull",
  landmakr: "Land Maker",
  ldrun: "Lode Runner (set 1)",
  ldrun2: "Lode Runner II",
  ldrun3: "Lode Runner III",
  ldrun4: "Lode Runner IV",
  lethalth: "Lethal Thunder",
  liblrabl: "Libble Rabble",
  lightbr: "Light Bringer",
  lizwiz: "Lizard Wizard",
  lkage: "Legend of Kage (US)",
  llander: "Lunar Lander",
  locomotn: "Loco-Motion",
  loderndf: "Lode Runner - The Dig Fight (ver. A)",
  loht: "Legend of Hero Tonma (World)",
  lwings: "Legendary Wings (World)",
  macross2: "Macross II",
  mainevt2p: "Main Event (2 Players)",
  mario: "Mario Bros. (US)",
  mazinger: "Mazinger Z (World)",
  metamrph: "Metamorphic Force (World)",
  metmqstr: "Metal Quest",
  mgcrystl: "Magical Crystals (World)",
  mhavoc: "Major Havoc",
  mikie: "Mikie",
  milliped: "Millipede (set 1)",
  missile: "Missile Command (rev 3)",
  moomesa: "Moo Mesa",
  mrgoemon: "Mr. Goemon (Japan)",
  mwalk: "Michael Jackson's Moonwalker (World)",
  mystwarr: "Mystic Warriors (World)",
  narc: "NARC (rev 7.00)",
  nibbler: "Nibbler",
  ninjak: "Ninja Kids (World)",
  ninjakd2: "Ninja-kun Ashura no Shou",
  ninjakun: "Ninja-kun Ashura no Shou",
  nitedrvr: "Night Driver",
  nitrobal: "Nitro Ball (US)",
  nob: "Noboranka",
  nrallyx: "New Rally-X",
  nslashers: "Night Slashers (World)",
  nspirit: "Ninja Spirit (World)",
  osman: "Osman",
  outfxies: "Out Foxies (World)",
  pacland: "Pac-Land (World)",
  pbobble3: "Puzzle Bobble 3 (World)",
  penbros: "Penguin Brothers (Japan)",
  pitfight: "Pit Fighter (rev 9)",
  pleiads: "Pleiads",
  pooyan: "Pooyan",
  punkshot2: "Punk Shot (World 2 Players)",
  puyo: "Puyo Puyo (Japan)",
  puzzloop: "Puzz Loop (Japan)",
  qix: "Qix (set 1)",
  quartet2: "Quartet 2 (Japan)",
  radm: "Rad Mobile",
  rambo3: "Rambo III (Europe)",
  rampart2p: "Rampart (2 Players)",
  rbisland: "Rainbow Islands (World, Joystick)",
  renegade: "Renegade (US)",
  ringking: "Ring King (US)",
  riotcity: "Riot City (Japan)",
  robocop: "RoboCop (World)",
  robocop2: "RoboCop 2 (World)",
  rocnrope: "Roc'n Rope",
  rohga: "Rohga - Armor Force",
  rthun2: "Rolling Thunder 2",
  rthunder: "Rolling Thunder (New Version)",
  rushatck: "Rush'n Attack (US)",
  sabotenb: "Saboten Bombers (set 1)",
  scobra: "Super Cobra",
  seawolft: "Sea Wolf (set 1)",
  seganinj: "Sega Ninja (World)",
  seicross: "Seicross",
  sf: "Street Fighter (World)",
  shadfrce: "Shadow Force (World)",
  shangon: "Shanghai III (Japan)",
  sharrier: "Space Harrier",
  shdancer: "Shadow Dancer (World)",
  shollow: "Skull Hollow",
  sidearms: "Side Arms - Hyper Dyne (World)",
  simpsons2p: "The Simpsons (2 Players World)",
  sinistar: "Sinistar (rev 3)",
  skykid: "Sky Kid (World)",
  slapshot: "Slap Shot (Japan)",
  slyspy: "Sly Spy (US)",
  smashtv: "Smash T.V. (rev 8.00)",
  solrwarr: "Solar Warrior",
  sonic: "Sonic the Hedgehog (Mega-Tech)",
  sonicfgt: "Sonic Championship (USA)",
  sonson: "Son Son",
  spacedx: "Space Invaders DX (Japan, v2.1)",
  spcinv95: "Space Invaders '95 (Japan)",
  spidman: "Spider-Man - The Video Game (World)",
  splatter: "Splatter House (World)",
  spnchout: "Super Punch-Out!! (World)",
  spyhunt: "Spy Hunter",
  spyhunt2: "Spy Hunter 2",
  srumbler: "The Speed Rumbler (set 1)",
  ssridersubc: "Sunset Riders (2 Players ver EBC)",
  starwars: "Star Wars (set 1)",
  stdragon: "Steel Dragon",
  stmblade: "Storm Blade (US)",
  superpac: "Super Pac-Man",
  sxevious: "Super Xevious",
  szaxxon: "Super Zaxxon",
  tankfrce: "Tank Force (US)",
  tapper: "Tapper (Budweiser, set 1)",
  tetrisp2: "Tetris Plus 2 (World)",
  tgm2p: "Tetris The Grand Master 2 - The Absolute Plus",
  thndrbld: "Thunder Blade",
  thundfox: "Thunder Fox (World)",
  tigeroad: "Tiger Road (US)",
  timeplt: "Time Pilot",
  tmnt22pu: "Teenage Mutant Ninja Turtles - Turtles in Time (2 Players ver UDA)",
  tnzs: "The New Zealand Story (World, old version)",
  todruaga: "Tower of Druaga",
  toobin: "Toobin' (rev 3)",
  totcarn: "Total Carnage",
  trackfld: "Track & Field",
  trojan: "Trojan (US)",
  tumblep: "Tumble Pop (World)",
  twocrude: "Two Crude Dudes (World)",
  uccops: "Undercover Cops (World)",
  upndown: "Up'n Down",
  valkyrie: "Valkyrie no Densetsu (Japan)",
  vball: "V'Ball (US)",
  vendetta2pu: "Vendetta (World 2 Players, ver. W)",
  viostorm: "Violent Storm (World)",
  volfied: "Volfied (World, revision 1)",
  vulcan: "Vulcan Venture (World)",
  wb3: "Wonder Boy III - Monster Lair (World)",
  wbml: "Wonder Boy in Monster Land",
  wboy: "Wonder Boy (set 1)",
  wildfang: "Wild Fang",
  wizdfire: "Wizard Fire (US)",
  wwfsstar: "WWF Superstars (US)",
  wwfwfest: "WWF WrestleFest (World)",
  xmen2pa: "X-Men (2 Players ver AAA)",
  xmultipl: "X Multiply (World)",
  xybots: "Xybots (rev 2)",
  yiear: "Yie Ar Kung-Fu (World)",
  zookeep: "Zoo Keeper (set 1)",
};

function headRequest(url: string): Promise<number> {
  return new Promise((resolve, reject) => {
    const req = https.request(url, { method: "HEAD", timeout: 5000 }, (res) => {
      resolve(res.statusCode ?? 0);
    });
    req.on("error", (err: NodeJS.ErrnoException) => {
      if (err.code === "ENOTFOUND" || err.code === "ECONNREFUSED") reject(err);
      else resolve(0);
    });
    req.on("timeout", () => { req.destroy(); resolve(0); });
    req.end();
  });
}

async function main() {
  console.log("=== libretro CDN 썸네일 존재 여부 검증 ===\n");

  const CDN_BASE = "https://thumbnails.libretro.com/MAME/Named_Snaps/";
  let verified = 0;
  let failed = 0;
  const failedGames: string[] = [];

  for (const [shortcode, englishName] of Object.entries(NEW_MAME_THUMBNAIL_NAMES)) {
    const urlName = englishName.replace(/:/g, "_").replace(/\//g, "_");
    const url = CDN_BASE + encodeURIComponent(urlName + ".png").replace(/%20/g, "%20");

    try {
      const status = await headRequest(url);
      if (status === 200) {
        verified++;
      } else {
        failed++;
        failedGames.push(`${shortcode}: ${englishName} (HTTP ${status})`);
        process.stdout.write("❌");
      }
    } catch {
      failed++;
      failedGames.push(`${shortcode}: ${englishName} (error)`);
      process.stdout.write("❌");
    }

    // Rate limit: 100ms delay between requests
    await new Promise(r => setTimeout(r, 100));
  }

  console.log(`\n\n검증 완료: ${verified}개 성공, ${failed}개 실패`);
  if (failedGames.length > 0) {
    console.log("\n실패한 게임:");
    failedGames.forEach(g => console.log(`  ${g}`));
  }
}

main().catch(console.error);
